name: Data Preprocessing Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn joblib
    
    - name: Run preprocessing
      run: |
        python preprocessing/automate_alpian-khairi.py
    
    - name: Commit processed data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/diabetes_preprocessed.csv
        git add preprocessing/diabetes_preprocessed_objects.pkl
        git add preprocessing/diabetes_preprocessed_report.txt
        git add diabetes_preprocessing.log
        git add data/diabetes_raw.csv
        if ! git diff --staged --quiet; then
          git commit -m "Update preprocessed data and artifacts"
          git push
        else
          echo "No changes to commit"
        fi