name: Data Preprocessing Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn
    
    - name: Run preprocessing
      run: |
        python preprocessing/automate_alpian-khairi.py
    
    - name: Commit processed data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/diabetes_preprocessing.csv
        git diff --staged --quiet || git commit -m "Update preprocessed data"
        git push